C**** DAGCOM
C**** DIAGNOSTICS COMMON BLOCK

      MODULE DAGCOM

      USE E001M12_COM, only : im,jm,lm,imh
     &   ,lm_req ! lm_req will come from a radiation module

      IMPLICIT NONE
      
C**** DIAGNOSTIC ARRAYS

      INTEGER, PARAMETER :: KAJ=94
      DOUBLE PRECISION, DIMENSION(JM,KAJ) :: AJ,BJ,CJ

      INTEGER, PARAMETER :: NREG=24
      DOUBLE PRECISION, DIMENSION(NREG,KAJ) :: DJ

      INTEGER, PARAMETER :: KAPJ=3
      DOUBLE PRECISION, DIMENSION(JM,KAPJ) :: APJ

      INTEGER, PARAMETER :: KAJL=57
      DOUBLE PRECISION, DIMENSION(JM,LM,KAJL) :: AJL

      INTEGER, PARAMETER :: KASJL=4
      DOUBLE PRECISION, DIMENSION(JM,LM_REQ,KASJL) :: ASJL

      INTEGER, PARAMETER :: KAIJ=100
      DOUBLE PRECISION, DIMENSION(IM,JM,KAIJ) :: AIJ

      INTEGER, PARAMETER :: KAIL=16
      DOUBLE PRECISION, DIMENSION(IM,LM,KAIL) :: AIL

      INTEGER, PARAMETER :: KAIJG=29
      DOUBLE PRECISION, DIMENSION(IM,JM,KAIJG) :: AIJG

      DOUBLE PRECISION, DIMENSION(20,100) :: ENERGY

      INTEGER, PARAMETER :: KCON=36
      DOUBLE PRECISION, DIMENSION(JM,KCON) :: CONSRV

      DOUBLE PRECISION, DIMENSION((IMH+1),20,8) :: SPECA

      integer, parameter :: NHEMI=2
      DOUBLE PRECISION, DIMENSION(8,NHEMI) :: ATPE

      integer, parameter :: HR_IN_DAY=24
      integer, parameter :: NDLYVAR=63
      integer, parameter :: NDLYPT=4
      double precision, dimension(HR_IN_DAY,NDLYVAR,NDLYPT) :: adaily

      INTEGER, PARAMETER :: KAJK=51
      DOUBLE PRECISION, DIMENSION(JM,LM,KAJK) :: AJK

      INTEGER, PARAMETER :: KAIJK=6
      DOUBLE PRECISION, DIMENSION(IM,JM,LM,KAIJK) :: AIJK

      INTEGER, PARAMETER :: KAIJL=5
      DOUBLE PRECISION, DIMENSION(IM,JM,LM,KAIJL) :: AIJL

      integer, parameter :: NWAV_DAG=10
      INTEGER, PARAMETER :: KAJLSP=3
      DOUBLE PRECISION, DIMENSION(JM,LM,NWAV_DAG,KAJLSP) :: AJLSP

      integer, parameter :: N12HRS_IN_31DAY=62
      integer, parameter :: RE_AND_IM=2
      DOUBLE PRECISION,
     &     DIMENSION(RE_AND_IM,N12HRS_IN_31DAY,NWAV_DAG,12) :: WAVE

      INTEGER, PARAMETER :: KACC=
     &     JM*KAJ + JM*KAJ + JM*KAJ + 24*KAJ +
     &     JM*KAPJ +
     &     JM*LM*KAJL +
     &     JM*LM_REQ*KASJL +
     &     IM*JM*KAIJ +
     &     IM*LM*KAIL +
     &     IM*JM*KAIJG +
     &     20*100 +
     &     JM*KCON +
     &     (IMH+1)*20*8 +
     &     8*NHEMI +
     &     HR_IN_DAY*NDLYVAR*NDLYPT +
     &     RE_AND_IM*N12HRS_IN_31DAY*NWAV_DAG*12 +
     &     JM*LM*KAJK +
     &     IM*JM*LM*KAIJK +
     &     IM*JM*LM*KAIJL +
     &     JM*LM*NWAV_DAG*KAJLSP

      COMMON /ACCUM/ AJ,BJ,CJ,DJ,APJ,AJL,ASJL,AIJ,AIL,
     &  AIJG,ENERGY,CONSRV,SPECA,ATPE,ADAILY,WAVE,
     &  AJK,AIJK,AIJL,AJLSP

      DOUBLE PRECISION, DIMENSION(IM,JM,2) :: TSFREZ

      INTEGER, PARAMETER :: KTD=8
      DOUBLE PRECISION, DIMENSION(IM,JM,KTD) :: TDIURN

      INTEGER, DIMENSION(IM,JM) :: JREG
      COMMON /REGION/ JREG
      INTEGER, DIMENSION(42,50) :: KEYNR
      INTEGER, DIMENSION(12) :: KDIAG
      COMMON /KEYS/ KEYNR,KDIAG

      END MODULE DAGCOM
