C**** DAGCOM
C**** DIAGNOSTICS COMMON BLOCK

      MODULE DAGCOM

      USE E001M12_COM, only : im,jm,lm,imh

      USE RADNCB, only : LM_REQ

      IMPLICIT NONE
      
C**** DIAGNOSTIC ARRAYS

      INTEGER, PARAMETER :: KAJ=94
      DOUBLE PRECISION, DIMENSION(JM,KAJ) :: AJ,BJ,CJ

      INTEGER, PARAMETER :: NREG=24
      DOUBLE PRECISION, DIMENSION(NREG,KAJ) :: DJ

      INTEGER, PARAMETER :: KAPJ=3
      DOUBLE PRECISION, DIMENSION(JM,KAPJ) :: APJ

      INTEGER, PARAMETER :: KAJL=57
      DOUBLE PRECISION, DIMENSION(JM,LM,KAJL) :: AJL

      INTEGER, PARAMETER :: KASJL=4
      DOUBLE PRECISION, DIMENSION(JM,LM_REQ,KASJL) :: ASJL

      INTEGER, PARAMETER :: KAIJ=100
      DOUBLE PRECISION, DIMENSION(IM,JM,KAIJ) :: AIJ
 
      INTEGER, PARAMETER :: KAIL=16
      DOUBLE PRECISION, DIMENSION(IM,LM,KAIL) :: AIL

      INTEGER, PARAMETER :: KAIJG=29
      DOUBLE PRECISION, DIMENSION(IM,JM,KAIJG) :: AIJG

C NEHIST = (TROPO/STRAT)X(ZKE/EKE/SEKE/ZPE/EPE)X(SH/NH)
      INTEGER, PARAMETER :: NEHIST=20
      INTEGER, PARAMETER :: HIST_DAYS=100
      DOUBLE PRECISION, DIMENSION(NEHIST,HIST_DAYS) :: ENERGY

      INTEGER, PARAMETER :: KCON=42
      DOUBLE PRECISION, DIMENSION(JM,KCON) :: CONSRV

      INTEGER, PARAMETER :: KSPECA=20
      INTEGER, PARAMETER :: NSPHER=8
      DOUBLE PRECISION, DIMENSION((IMH+1),KSPECA,NSPHER) :: SPECA

      INTEGER, PARAMETER :: KTPE=8 ! a P.E. subset of KSPECA
      integer, parameter :: NHEMI=2
      DOUBLE PRECISION, DIMENSION(KTPE,NHEMI) :: ATPE

      integer, parameter :: HR_IN_DAY=24
      integer, parameter :: NDLYVAR=63
      integer, parameter :: NDLYPT=4
      double precision, dimension(HR_IN_DAY,NDLYVAR,NDLYPT) :: adaily

      INTEGER, PARAMETER :: KAJK=51
      DOUBLE PRECISION, DIMENSION(JM,LM,KAJK) :: AJK

      INTEGER, PARAMETER :: KAIJK=6
      DOUBLE PRECISION, DIMENSION(IM,JM,LM,KAIJK) :: AIJK

      INTEGER, PARAMETER :: KAIJL=5
      DOUBLE PRECISION, DIMENSION(IM,JM,LM,KAIJL) :: AIJL

      integer, parameter :: NWAV_DAG=10
      INTEGER, PARAMETER :: KAJLSP=3
      DOUBLE PRECISION, DIMENSION(JM,LM,NWAV_DAG,KAJLSP) :: AJLSP

      integer, parameter :: N12HRS_IN_31DAY=62
      integer, parameter :: RE_AND_IM=2
      integer, parameter :: KWP=12
      DOUBLE PRECISION,
     &     DIMENSION(RE_AND_IM,N12HRS_IN_31DAY,NWAV_DAG,KWP) :: WAVE

      INTEGER, PARAMETER :: KACC=
     &     JM*KAJ + 
     &     JM*KAJ + 
     &     JM*KAJ + 
     &     NREG*KAJ + 
     &     JM*KAPJ + 
     &     JM*LM*KAJL + 
     &     JM*LM_REQ*KASJL + 
     &     IM*JM*KAIJ + 
     &     IM*LM*KAIL + 
     &     IM*JM*KAIJG + 
     &     NEHIST*HIST_DAYS + 
     &     JM*KCON + 
     &     (IMH+1)*KSPECA*NSPHER + 
     &     KTPE*NHEMI + 
     &     HR_IN_DAY*NDLYVAR*NDLYPT + 
     &     RE_AND_IM*N12HRS_IN_31DAY*NWAV_DAG*KWP + 
     &     JM*LM*KAJK + 
     &     IM*JM*LM*KAIJK + 
     &     IM*JM*LM*KAIJL + 
     &     JM*LM*NWAV_DAG*KAJLSP

      COMMON /ACCUM/ AJ,BJ,CJ,DJ,APJ,AJL,ASJL,AIJ,AIL,
     &  AIJG,ENERGY,CONSRV,SPECA,ATPE,ADAILY,WAVE,
     &  AJK,AIJK,AIJL,AJLSP

      DOUBLE PRECISION, DIMENSION(IM,JM,2) :: TSFREZ

      INTEGER, PARAMETER :: KTD=8
      DOUBLE PRECISION, DIMENSION(IM,JM,KTD) :: TDIURN

      INTEGER, DIMENSION(IM,JM) :: JREG

      INTEGER, PARAMETER :: NKEYNR=42
      INTEGER, PARAMETER :: NKEYMO=50
      INTEGER, DIMENSION(NKEYNR,NKEYMO) :: KEYNR
      INTEGER, DIMENSION(12) :: KDIAG

      INTEGER :: KREG
      CHARACTER*4 TITREG*80,NAMREG(2,23)

!@var IWRITE,JWRITE,ITWRITE grid point and surface type for diag. output
      INTEGER :: IWRITE = 0, JWRITE = 0, ITWRITE = 0
!@var QCHECK TRUE for running diagnostic checks
      LOGICAL :: QCHECK = .FALSE.

!@var IJ_xxx AIJ diagnostic names
      INTEGER :: IJ_RSOI, IJ_RSNW, IJ_SNOW, IJ_SHDT, IJ_PREC, IJ_EVAP,
     *     IJ_SSAT, IJ_BETA,  IJ_SLP1,  IJ_P4UV, IJ_PRES, IJ_PHI1K,
     *     IJ_PHI850,IJ_PHI700, IJ_PHI500, IJ_PHI300, IJ_PHI100,
     *     IJ_PHI30,IJ_T850,IJ_PMCCLD, IJ_CLDTPPR, IJ_CLDCV, IJ_PEV,
     *     IJ_TRNFP0, IJ_SRTR,IJ_NETH, IJ_SRNFP0, IJ_SRINCP0, IJ_SRNFG,
     *     IJ_SRINCG, IJ_TG1,IJ_RSIT, IJ_TDSL, IJ_DTDP, IJ_RUNE, IJ_TS1,
     *     IJ_RUNLI, IJ_WS,IJ_TS, IJ_US, IJ_VS, IJ_SLP,IJ_UJET, IJ_VJET,
     *     IJ_PCLDL, IJ_PCLDM, IJ_PCLDH, IJ_BTMPW, IJ_SRREF, IJ_ODATA4,
     *     IJ_TAUS, IJ_TAUUS, IJ_TAUVS, IJ_GWTR, IJ_QS, IJ_STRNGTS,
     *     IJ_ARUNU, IJ_DTGDTS, IJ_PUQ, IJ_PVQ, IJ_TGO, IJ_MSI2, IJ_WLM,
     *     IJ_TGO2,IJ_EVAPO, IJ_EVAPI, IJ_EVAPLI, IJ_EVAPE, IJ_F0OC,
     *     IJ_F0OI,IJ_F0LI, IJ_F0E, IJ_F1LI, IJ_SNWF, IJ_TSLI, IJ_ERUN2,
     *     IJ_SHDTLI, IJ_EVHDT, IJ_TRHDT, IJ_TMAX, IJ_TMIN, IJ_TMNMX,
     *     IJ_PEVAP,IJ_TMAXE, IJ_WMSUM, IJ_PSCLD, IJ_PDCLD, IJ_DCNVFRQ,
     *     IJ_SCNVFRQ, IJ_EMTMOM, IJ_SMTMOM, IJ_FPEU, IJ_FPEV, IJ_FMU,
     *     IJ_FMV,IJ_FQU, IJ_FQV, IJ_FGZU, IJ_FGZV 
!@var NAME_IJ Names of IJ diagnostics
      CHARACTER*7 NAME_IJ(KAIJ)
!@var IA_IJ IDACC indexes for IJ diagnostics
      INTEGER IA_IJ(KAIJ)

      END MODULE DAGCOM
