E001M16.R GISS Model E  strat.H2O added                rar 2/01/02

E001M16: modelE, dry cnv, 16 lyrs-> .3 mb, no GW drag, full Sdrag

Preprocessor Options
!#define TRACERS_ON                  ! include tracers code
End Preprocessor Options

Object modules: (in order of decreasing priority)
RES_M16T  ! horiz/vert resolution: 4x5, 16 lrs->.3mb, NO GWdrag
MODEL_COM GEOM_B IORSF              ! model variables and geometry
MODELE                              ! Main and model overhead
PARAM PARSER                        ! parameter database
ATMDYN_COM ATMDYN MOMEN2ND          ! atmospheric dynamics
QUS_COM QUSDEF QUS_DRV              ! advection of tracers
TQUS_DRV                            ! advection of Q
CLOUDS CLOUDS_DRV CLOUDS_COM        ! clouds modules
SURFACE FLUXES                      ! surface calculation and fluxes
GHY_COM GHY_DRV GHY                 ! land surface and soils
VEG_DRV VEG_COM VEGETATION          ! vegetation
PBL_COM PBL_DRV PBL                 ! atmospheric pbl
! pick exactly one of the next 2 choices: ATURB or DRYCNV
! ATURB                             ! turbulence in whole atmosphere
DRYCNV                              ! drycnv
LAKES_COM LAKES                     ! lake modules
SEAICE SEAICE_DRV                   ! seaice modules
LANDICE LANDICE_DRV                 ! land ice modules
OCEAN OCNML                         ! ocean modules
SNOW_DRV SNOW                       ! snow model
RAD_COM RAD_DRV RADIATION           ! radiation modules
DIAG_COM DIAG DEFACC DIAG_PRT       ! diagnostics
CONST FFT72 UTILDBL SYSTEM          ! utilities
POUT                                ! post-processing output

Data input files:
AIC=AIC.RES_M16b.D771201      ! initial conditions (atm.)
GIC=GIC.rsfB357M12.1DEC1956.1.ext ! initial conditions (ground)
! OHT=OTSPEC.RunIDM12.M250D   ! hor.heat transp.  not needed if ocn prescribed
OCNML=Z1O.B4X5.cor          ! mixed layer depth,needed for post-processing only
OSST=OST4X5.B.1946-55avg.Hadl1.1 ! prescr. climatological ocean (1 yr of data)
SICE=SICE4X5.B.1946-55avg.Hadl1.1 ! prescr. climatological sea ice
CDN=CD4X500S VEG=V72X46.1.cor2
SOIL=S4X50093 TOPO=Z72X46N.cor4 ! bdy.cond
REG=REG4X5           ! special regions-diag
RVR=RD4X525.RVR      ! river direction file
RADN1=sgpgxg.table8    ! rad.tables
RADN2=radfil33k                   !     8/2003 version
RADN3=miescatpar.abcdv
RADN5=TROAER.1875-1990.Jun2002
RADN6=dust8.tau9x8x13
RADN7=STRATAER.VOL.1850-1999.Apr02
RADN8=cloud.epsilon4.72x46
RADN9=solar.lean02.ann.uvflux    ! need KSOLAR=2
RADNE=topcld.trscat8
! new ozone files (minimum 1, maximum 9 files)
O3file_01=aug2003_o3_shindelltrop_72x46x18x12_1850
O3file_02=aug2003_o3_shindelltrop_72x46x18x12_1890
O3file_03=aug2003_o3_shindelltrop_72x46x18x12_1910
O3file_04=aug2003_o3_shindelltrop_72x46x18x12_1930
O3file_05=aug2003_o3_shindelltrop_72x46x18x12_1950
O3file_06=aug2003_o3_shindelltrop_72x46x18x12_1960
O3file_07=aug2003_o3_shindelltrop_72x46x18x12_1970
O3file_08=aug2003_o3_shindelltrop_72x46x18x12_1980
O3file_09=aug2003_o3_shindelltrop_72x46x18x12_1990
O3trend=aug2003_o3timetrend_46x18x2412_1850_2050
GHG=GHG.1850-2050.Mar2002
dH2O=dH2O_by_CH4_monthly
TOP_INDEX=top_index_72x46.ij

Label and Namelist:
E001M16 (strat.H2O - dry cnv - Sdrag->20mb, no GW drag)
R=00BG/B
DTFIX=180
&&PARAMETERS
X_SDRAG=.00025,.000025  ! used above P(P)_sdrag mb (and in top layer)
C_SDRAG=.000025 ! constant SDRAG above PTOP=150mb
P_sdrag=0.      ! linear SDRAG only in top layer (except near poles)
PP_sdrag=20.    ! linear SDRAG above PP_sdrag mb near poles
ANG_sdrag=1     ! if 1: SDRAG conserves ang.momentum by adding loss below PTOP

KOCEAN=0
U00ice=.55   ! tune this first to get reas.alb/cldcvr (range: .4-.6), then
HRMAX=450.   ! tune this to get rad.equilibrium (range: 100.-1500. meters)
! HRMAX=400.   ! try this for the 18 layer model (after changing M16 -> M18)

H2ObyCH4=1.     ! activates strat.H2O generated by CH4
KSIALB=0        ! 6-band albedo (Hansen) (=1 A.Lacis orig. 6-band alb)
KSOLAR=2

NIsurf=2        ! 4 for M18, 6 for M20,M24 (increase if layer 1 gets thinner)
DT=300.         ! from default: DTsrc=3600.,
dt_UVfilter=300.

SUBDD='SLP'     ! save SLP at sub-daily frequency
NSUBDD=12       ! saving sub-daily diags 12hrly
Kvflxo=1        ! saving VFLXO (daily)
KCOPY=2         ! saving acc + rsf
isccp_diags=1   ! activates coll. of ISCCP cloud data
&&END_PARAMETERS

 &INPUTZ
   YEARI=1949,MONTHI=12,DATEI=1,HOURI=0, ! IYEAR1=YEARI (default)
   YEARE=1956,MONTHE=1,DATEE=1,HOURE=0,  KDIAG=0,2,2,9*0,9,
   ISTART=2,IRANDI=0, YEARE=1949,MONTHE=12,DATEE=1,HOURE=1,
 &END
