C**** E001M12_COM
C**** COMMON BLOCK    4x5 deg Model  - Real*8 - VDATA:10->11+1

      MODULE E001M12_COM

C**** TO CHANGE THE GRID, MODIFY THE NEXT LINE ONLY
      INTEGER, PARAMETER :: IM=72,JM=46,LM=12, IMH=IM/2
      integer, parameter :: lmom = 9 ! for deep ocean diffusion  
C**** IM,JM,LM LIMITED TO 72,46,36 RESPECTIVELY BY RADCOM & SIGmas

C**** THERE ARE 100 INTEGER PARAMETERS IN COMMON (JC-ARRAY)
      INTEGER ::
     *                IM0,JM0,LM0,JMM1,LMM1,    LS1,LTM,LBLM,LMCM,LSSM,
     *  KOCEAN,KDISK,KEYCT,KACC0,KCOPY,  IRAND,IJRA,MFILTR,NDYN,NCNDS,
     *  NRAD,NSURF,NGRND,NFILTR,NDAA,   NDA5D,NDA5K,NDA5S,NDA4,NDASF,
     *  MLAST,MDYN,MCNDS,MRAD,MSURF,    MDIAG,MELSE,MODRD,MODD5K,MODD5S,
     *  IYEAR,IDAY,IDAY0,JYEAR,JYEAR0,  JDAY,JDATE,JDATE0,NSTEP,MRCH,
     *  KTACC0
      INTEGER, DIMENSION(3) :: IDUM
      INTEGER, DIMENSION(13) :: NDZERO,NDPRNT
      INTEGER, DIMENSION(2,4) :: IJD6
      INTEGER, DIMENSION(12) :: IDACC
      COMMON /IPARMB/ IM0,JM0,LM0,JMM1,LMM1,    LS1,LTM,LBLM,LMCM,LSSM,
     *  KOCEAN,KDISK,KEYCT,KACC0,KCOPY,  IRAND,IJRA,MFILTR,NDYN,NCNDS,
     *  NRAD,NSURF,NGRND,NFILTR,NDAA,   NDA5D,NDA5K,NDA5S,NDA4,NDASF,
     *  MLAST,MDYN,MCNDS,MRAD,MSURF,    MDIAG,MELSE,MODRD,MODD5K,MODD5S,
     *  IYEAR,IDAY,IDAY0,JYEAR,JYEAR0,  JDAY,JDATE,JDATE0,NSTEP,MRCH,
     *  KTACC0,IDUM   ,NDZERO    ,NDPRNT    ,  IJD6     ,IDACC    

! handle for referring to integer parameters
      INTEGER, DIMENSION(100) :: JC
      EQUIVALENCE (JC,IM0)

C**** THERE ARE 161 REAL NUMBERS IN COMMON (RC-ARRAY)
      DOUBLE PRECISION ::
     *  TAU,TAU0,TOFDAY,TOFDY0,DT,      TAUP,TAUI,TAUE,TAUT,TAUO,
     *  TWOPIx,SDAYx,LHEx,LHMx,LHSx, RADIUSx,GRAVx,RGASx,KAPAx,OMEGAx,
     *  CCMCX,U00,S0X,CO2,SRCOR,        PTOP,PSF,PSDRAG,PTRUNC,AREAGx,
     *            XINT,DLATx,DLONx,       SKIPSE,USESLP,USEP,USET,FIM,
     *  RSDIST,SIND,COSD,DOPK
      DOUBLE PRECISION, DIMENSION(2) :: XCDNST
      DOUBLE PRECISION, DIMENSION(36) :: SIG
      DOUBLE PRECISION, DIMENSION(37) :: SIGE
      DOUBLE PRECISION, DIMENSION(4) :: TAUTR0
      DOUBLE PRECISION, DIMENSION(40) :: RDM2
      COMMON /RPARMB/
     *  TAU,TAU0,TOFDAY,TOFDY0,DT,      TAUP,TAUI,TAUE,TAUT,TAUO,
     *  TWOPIx,SDAYx,LHEx,LHMx,LHSx,  RADIUSx,GRAVx,RGASx,KAPAx,OMEGAx,
     *  CCMCX,U00,S0X,CO2,SRCOR,        PTOP,PSF,PSDRAG,PTRUNC,AREAGx,
     *  XCDNST   ,XINT,DLATx,DLONx,       SKIPSE,USESLP,USEP,USET,FIM,
     *  RSDIST,SIND,COSD,DOPK,     SIG    ,SIGE    ,TAUTR0   ,RDM2    

! handle for referring to real parameters
      DOUBLE PRECISION, DIMENSION(161) :: RC
      EQUIVALENCE (RC,TAU)

      CHARACTER*4 XLABEL,NAMD6,JMONTH,JMNTH0
      COMMON /TEXT/ XLABEL(33),NAMD6(4),JMONTH,JMNTH0

! handles for referring to text parameters
      CHARACTER*8 LABEL1*16
      CHARACTER CLABEL*4
      DIMENSION CLABEL(39)
      EQUIVALENCE (CLABEL,XLABEL,LABEL1)

c      DOUBLE PRECISION, DIMENSION(JM) ::
c     *  RAPVS,RAPVN,RAVPS,RAVPN,FCOR,
c     *  DXYP,DXP,DYP,DXYS,SINP,LAT,
c     *  DXYV,DXV,DYV,DXYN,COSP,COSV
c      COMMON /GEOMCB/
c     *  RAPVS,RAPVN,RAVPS,RAVPN,FCOR,
c     *  DXYP,DXP,DYP,DXYS,SINP,LAT,
c     *  DXYV,DXV,DYV,DXYN,COSP,COSV

      DOUBLE PRECISION, DIMENSION(IM,JM) :: FLAND,FOCEAN,FLICE,FLAKE
     *     ,FEARTH,ZATMO
      DOUBLE PRECISION, DIMENSION(IM,JM,5) :: ODATA
      DOUBLE PRECISION, DIMENSION(IM,JM,16) :: GDATA
      DOUBLE PRECISION, DIMENSION(IM,JM,12) :: BLDATA
      DOUBLE PRECISION, DIMENSION(IM,JM,11) :: VDATA
      DOUBLE PRECISION, DIMENSION(IM,JM) :: WFCS,Z1O,Z12O
      COMMON /BNDYCB/ FLAND,FOCEAN,FLICE,FLAKE,FEARTH,ZATMO,ODATA,GDATA,
     *     BLDATA,VDATA,WFCS,Z1O,Z12O

      INTEGER, PARAMETER :: LM_REQ=3 ! # radiation-only layers
      DOUBLE PRECISION, DIMENSION(IM,JM,LM_REQ) :: RQT
      DOUBLE PRECISION, DIMENSION(IM,JM,LM+1) :: SRHR,TRHR
      DOUBLE PRECISION, DIMENSION(IM,JM,4) :: FSF
      COMMON /RADNCB/ RQT,SRHR,TRHR,FSF

      DOUBLE PRECISION, DIMENSION(36) :: DSIG
      DOUBLE PRECISION, DIMENSION(35) :: DSIGO
      COMMON /LAYACB/ DSIG,DSIGO

      DOUBLE PRECISION, DIMENSION(IM,JM,LM) :: U,V,T,Q
      DOUBLE PRECISION, DIMENSION(IM,JM) :: P
      COMMON /UVTPQ/ U,V,T,P,Q

C**** Some helpful arrays (arrays should be L first)

!@var  AM  Air mass of each box (kg/m^2)
!      REAL*8, DIMENSION(LM,IM,JM) :: AM
!@var  BYAM  1/Air mass (m^2/kg)
!      REAL*8, DIMENSION(LM,IM,JM) :: BYAM
!@var  PMID  Pressure at mid point of box (mb)
      REAL*8, DIMENSION(LM,IM,JM) :: PMID
!@var  PK   PMID**KAPA 
      REAL*8, SAVE,DIMENSION(LM,IM,JM) :: PK
!@var  PEUP  Pressure at lower edge of box (incl. surface) (mb)
      REAL*8, DIMENSION(LM+1,IM,JM) :: PEDN
!@var  PEK  PEUP**KAPA
      REAL*8, DIMENSION(LM+1,IM,JM) :: PEK
!@var  SQRTP  square root of P (used in diagnostics)
      REAL*8, DIMENSION(IM,JM) :: SQRTP

      END MODULE E001M12_COM
