E001r.R GISS Model E  strat.H2O added inst.frc          rar 2/01/02

E001r: radiation only, instantaneous forcing

Preprocessor Options
!#define TRACERS_ON                  ! include tracers code
End Preprocessor Options

Object modules: (in order of decreasing priority)
RES_M12                             ! horiz/vert resolution, 4x5deg, 12 layers -> 10mb
MODEL_COM GEOM_B IORSF              ! model variables and geometry
MODELE                              ! Main and model overhead
PARAM PARSER                        ! parameter database
ATMDYN_COM ATMDYN MOMEN2ND          ! atmospheric dynamics
QUS_COM QUSDEF QUS_DRV              ! advection of tracers
TQUS_DRV                            ! advection of Q
CLOUDS CLOUDS_DRV CLOUDS_COM        ! clouds modules
SURFACE FLUXES                      ! surface calculation and fluxes
GHY_COM GHY_DRV GHY                 ! land surface and soils
VEG_DRV VEG_COM VEGETATION          ! vegetation
PBL_COM PBL_DRV PBL                 ! atmospheric pbl
! pick exactly one of the next 2 choices: ATURB or DRYCNV
! ATURB                             ! turbulence in whole atmosphere
DRYCNV                              ! drycnv
LAKES_COM LAKES                     ! lake modules
SEAICE SEAICE_DRV                   ! seaice modules
LANDICE LANDICE_DRV                 ! land ice modules
ICEDYN_DRV ICEDYN  ! or: ICEDYN_DUM ! dynamic sea ice modules
OCEAN OCNML                         ! ocean modules
SNOW_DRV SNOW                       ! snow model
RAD_COM RAD_DRV RADIATION           ! radiation modules
DIAG_COM DIAG DEFACC DIAG_PRT       ! diagnostics
CONST FFT72 UTILDBL SYSTEM          ! utilities
POUT                                ! post-processing output

Data input files:
AIC=1JAN1951.rsfE001 ! just label records of control run are needed
OSST=OST4X5.B.1975-84avg.Hadl1.1  ! prescr. climatological ocean (1 yr of data)
SICE=SICE4X5.B.1975-84avg.Hadl1.1 ! prescr. climatological sea ice
CDN=CD4X500S    ! surf.drag coefficient
! VEG=V72X46.1.cor2   ! or:       ! vegetation fractions  (sum=1), need crops_yr=-1
VEG=V72X46.1.cor2_no_crops CROPS=CROPS_72X46N.cor4  ! veg. fractions, crops history
SOIL=S4X50093 TOPO=Z72X46N.cor4   ! soil/topography bdy.conds
REG=REG4X5                        ! special regions-diag
RVR=RD4X525.RVR                   ! river direction file
RADN1=sgpgxg.table8               ! rad.tables and history files
RADN2=kdist33.tautab8
RADN3=miescatpar.abcdv
RADN4=o3Prather1979-80.London1957-70
RADN5=TROAER.1875-1990.Jun2002
RADN6=dust8.tau9x8x13
RADN7=STRATAER.VOL.1850-1999.Apr02
RADN8=cloud.epsilon4.72x46
! RADN9=solar.lean99.uvflux        ! need KSOLAR<2
RADN9=solar.lean02.ann.uvflux      ! need KSOLAR=2
RADNA=O3.1850-2050.rec             ! with recovery of O3 after 2000
!  RADNA=O3.1850-2050.con          ! O3 'constant' after 2000
RADNB=o3WangJacob.1890.1979
RADNE=topcld.trscat8
GHG=GHG.1850-2050.Mar2002
dH2O=dH2O_by_CH4_monthly
TOP_INDEX=top_index_72x46.ij
RADJAN=E001/RADJAN1950    ! replace E001 by the control run
RADFEB=E001/RADFEB1950    ! assuming that the saved data are
RADMAR=E001/RADMAR1950    ! still in the original directory
RADAPR=E001/RADAPR1950
RADMAY=E001/RADMAY1950
RADJUN=E001/RADJUN1950
RADJUL=E001/RADJUL1950
RADAUG=E001/RADAUG1950
RADSEP=E001/RADSEP1950
RADOCT=E001/RADOCT1950
RADNOV=E001/RADNOV1950
RADDEC=E001/RADDEC1950

Label and Namelist:
E001r (inst.forcing run - control)


&&PARAMETERS
KOCEAN=0        ! ocn is prescribed
Kvflxo=0        ! don't touch this line
ocn_cycl=1      ! =0 if ocean varies from year to year

CO2X=1.
H2OstratX=1.

H2ObyCH4=1.     ! activates strat.H2O generated by CH4
KVEGA6=4        ! 6-band albedo (Hansen)
KSOLAR=2

! parameters that control the atmospheric/boundary conditions
! if set to 0, the current (day/) year is used: transient run
crops_yr=1979 ! if -1, crops in VEG-file is used
s0_yr=1979
s0_day=182
ghg_yr=1979
ghg_day=182
volc_yr=1979
volc_day=182
aero_yr=1979
o3_yr=1979
         ! most other parameters are irrelevant
NSUBDD=0            ! don't touch this line
KCOPY=2             ! saving acc + rsf
Kradia=1            ! use Kradia=2 for adj. forcing run
&&END_PARAMETERS

 &INPUTZ
   YEARE=1951,MONTHE=12,DATEE=1,HOURE=0,  ! assumed start: 12/1/1950
   ISTART=8, YEARE=1950,MONTHE=12,HOURE=6,IWRITE=1,JWRITE=1,ITWRITE=23,
 &END

It's important that DTsrc, NIrad, ItimeI are left as in the control
run so the input data are available when they are needed ! That's
why in this case ISTART=8 (start) looks more like ISTART=9 (restart).
The only parameters/input files that matter are the ones that affect
the radiation. It is their change whose instantaneous/adjusted
forcing is computed.
