E001M18A.R GISS Model E  2002 modelE cm*2/3                 rar  6/20/02

modelE with 18 lyrs, top at .1 mb - 1979 atmosphere/ocean
no gravity wave drag;     uses dry convection (rather than turbulence)
Sdrag: weak linear strat. drag in top layer, near poles down to 20 mb
       const drag above 150mb, lost ang.mom is added in below 150 mb
sealevel pressure filter applied every hour - UV-filter NOT used
6-band oice albedo; Hogstrom(1984) pbl drag, mom.drag*2/3
Note: Most of these choices may be changed using the PARAMETERs below.

Preprocessor Options
!#define TRACERS_ON                  ! include tracers code
End Preprocessor Options

Object modules: (in order of decreasing priority)
RES_M18AT ! horiz/vert resolution: 4x5, 18 lrs->.1mb, NO GWdrag
MODEL_COM GEOM_B IORSF              ! model variables and geometry
MODELE                              ! Main and model overhead
PARAM PARSER                        ! parameter database
ATMDYN_COM ATMDYN MOMEN2ND          ! atmospheric dynamics
QUS_COM QUSDEF QUS_DRV              ! advection of tracers
TQUS_DRV                            ! advection of Q
CLOUDS CLOUDS_DRV CLOUDS_COM        ! clouds modules
SURFACE FLUXES                      ! surface calculation and fluxes
GHY_COM GHY_DRV GHY                 ! land surface and soils
PBL_COM PBL_DRV PBL                 ! atmospheric pbl
! pick exactly one of the next 2 choices: ATURB or DRYCNV
! ATURB                             ! turbulence in whole atmosphere
DRYCNV                              ! drycnv
LAKES_COM LAKES                     ! lake modules
SEAICE SEAICE_DRV                   ! seaice modules
LANDICE LANDICE_DRV                 ! land ice modules
OCEAN OCNML                         ! ocean modules
SNOW                                ! snow model
RAD_COM RAD_DRV RADIATION           ! radiation modules
DIAG_COM DIAG DEFACC DIAG_PRT       ! diagnostics
CONST FFT72 UTILDBL SYSTEM          ! utilities
POUT                                ! post-processing output

Data input files:
AIC=AIC.RES_M18A.D771201   ! initial conditions (atm.)
GIC=GIC.E005gasA.1DEC1956x ! initial conditions (ground)
! OHT=OTSPEC.RunIDM12.M250D  ! hor.heat transp.  not needed if ocn prescribed
OCNML=Z1O.B4X5.cor         ! mixed layer depth,needed for post-processing only
OSST=OST4X5.B.1975-84avg.Hadl1.1 ! prescr. climatological ocean (1 yr of data)
SICE=SICE4X5.B.1975-84avg.Hadl1.1 ! prescr. climatological sea ice
CDN=CD4X500S VEG=V72X46.1.cor
SOIL=S4X50093 TOPO=Z72X46N.cor4 ! bdy.cond
REG=REG4X5           ! special regions-diag
RVR=RD4X525.RVR      ! river direction file
RADN1=sgpgxg.table8    ! rad.tables
RADN2=kdist33.tautabs4
RADN3=miescatpar.abcdv
RADN4=o3Prather1979-80.London1957-70
RADN5=TROAER.1875-1990.Jun2002
RADN6=dust8.tau9x8x13
RADN7=STRATAER.VOL.1850-1999.Apr02
RADN8=cloud.epsilon4.72x46
! RADN9=solar.lean99.uvflux          ! need KSOLAR<2
RADN9=solar.lean02.ann.uvflux    ! need KSOLAR=2
RADNA=O3.1850-2050.depl.rec       ! with recovery of O3 after 2000
!  RADNA=O3.1850-2050.depl.con    ! O3 'constant' after 2000
RADNB=o3WangJacob.1890.1979
RADNE=topcld.trscat8
GHG=GHG.1850-2050.Mar2002
dH2O=dH2O_by_CH4
TOP_INDEX=top_index_72x46.ij

Label and Namelist:
E001M18A (pbl cm*2/3 - 1979 atm/ocn)
       
DTFIX=180

&&PARAMETERS
X_SDRAG=.00025,.000025  ! used above P(P)_sdrag mb (and in top layer)
C_SDRAG=.00002  ! constant SDRAG above PTOP=150mb
P_sdrag=0.      ! linear SDRAG only in top layer (except near poles)
PP_sdrag=20.    ! linear SDRAG above PP_sdrag mb near poles
ANG_sdrag=1     ! if 1: SDRAG conserves ang.momentum by adding loss below PTOP

KOCEAN=0
xCDpbl=.666     ! tune surface mom.drag to get reas. SLP (990mb at 65S)
U00ice=.52      ! then tune this to get ann.alb near 30% (range: .4-.6)
HRMAX=800.      ! then tune this to get rad.balance (net heat zo=0 over ocn)
! HRMAX=800.      ! seems to work for atm.composition of 1979
! HRMAX=500.      ! if atm.composition of 1880 is used
! HRMAX=700.      ! if atm.composition of 1951 is used

H2ObyCH4=1.     ! activates strat.H2O generated by CH4
KVEGA6=3        ! 6-band albedo (Schramm)
KSOLAR=2
NIsurf=2        ! increase as layer 1 gets thinner
DT=300.         ! from default: DTsrc=3600.,
Ndisk=24        ! use =240 on COMPAQ with lsf-batch system

SUBDD='SLP'     ! save SLP at sub-daily frequency
NSUBDD=12       ! saving sub-daily diags 12hrly
Kvflxo=1        ! saving VFLXO (daily)
KCOPY=2         ! saving acc + rsf
isccp_diags=0   ! use =1 to activate coll. of ISCCP cloud data
nda5d=7         ! use =1 to get more precise conservation diagnostics
nda5s=7         ! use =1 to get more precise conservation diagnostics
! if the params below change, you may have to adjust HRMAX
s0_yr=1979      ! INcrease of HRMAX DEcreases net heat at z0
ghg_yr=1979     !             (and INcreases the plan. albedo)
ghg_day=182     ! DEcrease of U00ice has the same effect
s0_day=182
volc_yr=1979
volc_day=182
aero_yr=1979
o3_yr=1979
&&END_PARAMETERS

 &INPUTZ
   YEARI=1949,MONTHI=12,DATEI=1,HOURI=0, ! IYEAR1=YEARI (default)
   YEARE=1956,MONTHE=1,DATEE=1,HOURE=0,     KDIAG=0,2,2,9*0,
   ISTART=2,IRANDI=0, YEARE=1949,MONTHE=12,HOURE=1,
 &END
