E001qd.R GISS Model E                                 gas 06/00

E001qd: new modelE (Qflux version with deep diffusion)

Preprocessor Options
!#define TRACERS_ON                  ! include tracers code
End Preprocessor Options

Object modules: (in order of decreasing priority)
RES_M12                             ! horiz/vert resolution
MODEL_COM GEOM_B IORSF              ! model variables and geometry
MODELE                              ! Main and model overhead
PARAM PARSER                        ! parameter database
ATMDYN_COM ATMDYN MOMEN2ND          ! atmospheric dynamics
QUS_COM QUSDEF QUS_DRV              ! advection of tracers
TQUS_DRV                            ! advection of Q
CLOUDS CLOUDS_DRV CLOUDS_COM        ! clouds modules
SURFACE FLUXES                      ! surface calculation and fluxes
GHY_COM GHY_DRV GHY                 ! land surface and soils
PBL_COM PBL_DRV PBL                 ! atmospheric pbl
! pick exactly one of the next 2 choices:  ATURB or DRYCNV
! ATURB                             ! turbulence in whole atmosphere
DRYCNV                              ! drycnv
LAKES_COM LAKES                     ! lake modules
SEAICE SEAICE_DRV                   ! seaice modules
LANDICE LANDICE_DRV                 ! land ice modules
ICEDYN_DRV ICEDYN  ! or: ICEDYN_DUM ! land ice modules
OCEAN ODEEP                         ! ocean modules
SNOW_DRV SNOW                       ! snow model
RAD_COM RAD_DRV RADIATION           ! radiation modules
DIAG_COM DIAG DEFACC DIAG_PRT       ! diagnostics
CONST FFT72 UTILDBL SYSTEM          ! utilities
POUT                                ! post-processing output

Data input files:
! The next 3 lines depend on the preliminary runs (prescr./shallow ocean)
AIC=1JAN1961.rsfE001q               ! initial conditions (from qflux ISTART=4)
! AIC=1JAN1961.rsfE001qd            ! initial conditions (from qdeep ISTART=8)
OHT=OTSPEC.E001.M250D.1951-1955     ! horizontal ocean heat transports
TG3M=TG3M.E001q.19711980            ! created by 'mkdeep'
! OSST=OST4X5.B.1946-55avg.Hadl1.1 SICE=SICE4X5.B.1946-55avg.Hadl1.1 ! ocn
EDDY=ED4X5 ! Eddy diffusivity for deep ocean mixing
CDN=CD4X500S VEG=V72X46.1.cor2
SOIL=S4X50093 TOPO=Z72X46N.cor4 ! bdy.cond
REG=REG4X5           ! special regions-diag
RVR=RD4X525.RVR      ! river direction file
RADN1=sgpgxg.table8    ! rad.tables
RADN2=kdist33.tautab8
RADN3=miescatpar.abcdv
RADN4=o3Prather1979-80.London1957-70
RADN5=TROAER.1875-1990.Jun2002
RADN6=dust8.tau9x8x13
RADN7=STRATAER.VOL.1850-1999.Apr02
RADN8=cloud.epsilon4.72x46
! RADN9=solar.lean99.uvflux             ! need KSOLAR<2
RADN9=solar.lean02.ann.uvflux       ! need KSOLAR=2
RADNA=O3.1850-2050.depl.rec       ! with recovery of O3 after 2000
!  RADNA=O3.1850-2050.depl.con    ! O3 'constant' after 2000
RADNB=o3WangJacob.1890.1979
RADNE=topcld.trscat8
GHG=GHG.1850-2050.Mar2002
dH2O=dH2O_by_CH4_monthly
TOP_INDEX=top_index_72x46.ij

Label and Namelist:
E001qd (new modelE based on B402A - Qflux + deep diffusion)

DTFIX=300
&&PARAMETERS
! parameters set for q-flux ocean runs:
KOCEAN=1        ! ocn is predicted
Kvflxo=0        ! don't save VFLXO (daily) if ocn is predicted

! parameters that usually are the same as in E001 (spinup):

X_SDRAG=.00025,.000025  ! used above P(P)_sdrag mb (and in top layer)
C_SDRAG=0.      ! constant SDRAG above PTOP=150mb
P_sdrag=0.      ! linear SDRAG only in top layer (except near poles)
! PP_sdrag=20.  ! linear SDRAG above PP_sdrag mb near poles
ANG_sdrag=1     ! if 1: SDRAG conserves ang.momentum by adding loss below PTOP

xCDpbl=1.
U00ice=.60   ! use same values as in corr. run with climatological ocean
U00wtr=.80   ! use same values as in corr. run with climatological ocean
HRMAX=550.   ! use same values as in corr. run with climatological ocean

RWCLDOX=1.5  !  wtr cld particle size *3/2 over ocean
RICLDX=.3333 !  ice cld particle size * 1(at 0mb)->1/3(at 1000mb)

CO2X=1.
H2OstratX=1.

H2ObyCH4=1.     ! activates strat.H2O generated by CH4
KVEGA6=4        ! 6-band albedo (Hansen)
KSOLAR=2

! parameters that control the atmospheric composition
! if set to 0, the current (day/) year is used: transient run
s0_yr=1979
s0_day=182
ghg_yr=1979
ghg_day=182
volc_yr=1979
volc_day=182
aero_yr=1979
o3_yr=1979

DT_UVfilter=450.  ! usually same as DT (below)

! parameters that may have to be changed in emergencies:
DT=450.         ! from default: DTsrc=3600.,
NIsurf=2        ! increase as layer 1 gets thinner

! parameters that affect at most diagn. output:
Ndisk=24        ! use =240 on halem
SUBDD=' '     ! save SLP at sub-daily frequency
NSUBDD=0       ! saving sub-daily diags 12hrly
KCOPY=2         ! saving acc + rsf
isccp_diags=1   ! use =0 to save cpu time
nda5d=1         ! use =7 to save cpu time
nda5s=1         ! use =7 to save cpu time
&&END_PARAMETERS

 &INPUTZ
   YEARI=1950,MONTHI=1,DATEI=1,HOURI=0, !  from default: IYEAR1=YEARI
   YEARE=1956,MONTHE=1,DATEE=1,HOURE=0, KDIAG=0,2,2,9*0,9,
   YEARE=1950,MONTHE=2,
   ISTART=4,IRANDI=0, YEARE=1950,MONTHE=1,HOURE=1,IWRITE=1,JWRITE=1,
 &END
