C**** COMMON BLOCK SOMTQ                      9/98

      MODULE SOMTQ_COM

      USE E001M12_COM
     &     , only : im,jm,lm

      DOUBLE PRECISION, DIMENSION(IM,JM,LM) ::
     *  TX,TY,TZ,TXX,TYY,TZZ,TXY,TZX,TYZ
      COMMON/TADV/
     *  TX,TY,TZ,TXX,TYY,TZZ,TXY,TZX,TYZ
      DOUBLE PRECISION, DIMENSION(IM,JM,LM) ::
     *  QX,QY,QZ,QXX,QYY,QZZ,QXY,QZX,QYZ
      COMMON/QADV/
     *  QX,QY,QZ,QXX,QYY,QZZ,QXY,QZX,QYZ
      DOUBLE PRECISION, DIMENSION(IM,JM,LM,9) :: TMOM,QMOM
      EQUIVALENCE (TX,TMOM),(QX,QMOM)

      END MODULE SOMTQ_COM
