#!/bin/ksh
## FCO2_F90  Fortran Compilation into Object module    06/00
   if [ "$1" = '' ] ; then
echo "Usage: fco2_f90 file   Fortran Compile into Object module    06/00"
     exit ; fi
   if [ ! -f "$1" ] ; then  echo "File does not exist: $1" ; exit 1 ; fi
   umask 002
   Ffor="$1" ;  Ffor="${Ffor%%.*}" ;
   Flst="$Ffor.L" ; FLST="$Ffor.LST" ; FERR="$Ffor.ERR"
   Fobj="$Ffor.o" ; Ffor="$Ffor.f"
   if [ "$Ffor" != "$1" ] ; then 
    ftoc "$1" "$Ffor"
   fi
   optns='-O2 -64 -mips4 -c -static -listing -OPT:reorg_comm=off'
   if  f90 $optns -old_rl  "$Ffor" 2>"$FERR"
     then  echo "Object module: $Fobj   Created from: $1"
	   mv "$FERR" "$FLST"
     else  echo "Fortran error file: $FERR   Source file: $1"
           cat "$FERR" ; 
     fi
#   if [ -f "$Ffor" ] ; then mv "$Ffor" "$FLST" ; fi
   if [ -f "$Flst" ] ; then mv "$Flst" "$FLST" ; fi
#   if [ "$Ffor" = "$1" ] ; then mv "$Fsv" "$Ffor" ; fi
