#!/bin/ksh

CMRUNDIR='/u/cmrun'
if [[ -f ~/.modelErc ]]; then . ~/.modelErc; fi

if [[ $# -lt 2 || ! -d $CMRUNDIR/$1 ]] then 
    echo "Usage: pdE runID acc_files (list all; deflt path:$CMRUNDIR/runID)"
    exit
fi

runID=$1 ; shift
cd $CMRUNDIR/$runID
if [[ $? -ne 0 ]] then
    echo "could not cd to $CMRUNDIR/$runID ... aborting"
    exit 1
fi

if [[ $# -eq 1 ]] then 
  echo "processing $*"
else 
  echo "The following $# files are added up:"
  echo $*
fi

if [[ ! -s Ipd ]] ; then 
# set up a default file
cat <<EOF > Ipd
       

 &&PARAMETERS

 &&END_PARAMETERS
  
 &INPUTZ
 ISTART=-1,QDIAG=.true.,
 &END
EOF
fi

do_uln=0 ; if [[ ! -L TOPO ]] ; then ${runID}ln ; do_uln=1 ; fi
${runID}.exe $* < Ipd > pd.PRT
   if [[ ${do_uln} -eq 1 ]] ; then ${runID}uln ; fi

grep Diag pd.PRT  ; # report accumulation period   
