#!/bin/ksh

## defaults
  CMRUNDIR='/u/cmrun'
  if [[ -f ~/.modelErc ]]; then . ~/.modelErc; fi

  if [[ $# -ne 1 ]] ; then
      echo "Usage: sswE RUNID"
      echo "Stops the model run RUNID"
      exit; fi
  RUNID=$1

  if [[ ! -d $CMRUNDIR/$RUNID ]] ; then
      echo "Run directory not found: $CMRUNDIR/$RUNID"
      exit ; fi

  cd "$CMRUNDIR/$RUNID"
  echo "___OFF__" > sswOnOff
  echo "Set the switch to OFF position. Please wait for $RUNID to stop."
