#!/bin/sh

if [[ $# -ne 1 ]] ; then 
  echo "Usage: sswE RUNID"
  echo "will stop the run RUNID"
  exit;  fi

RUNID=$1
PID=`ps -ef | grep "/$RUNID[.]exe" | awk '{print $2}'`
if [[ $PID = '' ]] ; then 
  echo "$RUNID is not running on this machine"
  exit; fi

echo killing $PID
kill -15 $PID
echo "signal sent: please wait for $RUNID to stop"

