#!/bin/ksh
## uco2_f90   Update and fortran-Compile into Object module    06/00
  if [ "$1" = '' ] ; then
echo "Usage: uco2_f90 file    Update and Compile into Object module 06/00"
     exit ; fi
  umask 002
  upd $1
  Ffor="$1"
  Flst="$Ffor.L" ; FPRT="$Ffor.LST" ; FERR="$Ffor.ERR"
  Fobj="$Ffor.o" ; Ffor="$Ffor.f"
  optns='-O2 -64 -mips4 -c -static -listing -OPT:reorg_comm=off -old_rl'
  if  f90 $optns "$Ffor" 2>"$FERR"
     then  echo "Object module: $Fobj   Created from: $1"
#           cat "$FERR" ; 
	    mv "$FERR" "$Ffor"
     else  echo "Fortran error file: $FERR   Source file: $1"
           cat $FERR
           mv "$Fobj" "$Ffor" ; fi
   if [ -f "$Ffor" ] ; then mv "$Ffor" "$FPRT" ; fi
   if [ -f "$Flst" ] ; then mv "$Flst" "$FPRT" ; fi
