#!/bin/sh

DATADIR=/scrub/entdata
DATADIR_GCM=/u/cmrun

# overwrite settings with those in ~/.entrc file if present
if [ -f $HOME/.entrc ] ; then . $HOME/.entrc; fi


ln -s $DATADIR_GCM/V72X46_GISSEnt_nocrops VEG
ln -s $DATADIR_GCM/CROPS_72X46N.cor4 CROPS
ln -s $DATADIR_GCM/soil_textures_top30cm soil_textures

ln -s $DATADIR/CHJUN1950 CH
ln -s $DATADIR/DVISJUN1950 DVIS
ln -s $DATADIR/MP1JUN1950 MP1
ln -s $DATADIR/MP2JUN1950 MP2
ln -s $DATADIR/MP3JUN1950 MP3
ln -s $DATADIR/MP4JUN1950 MP4
ln -s $DATADIR/MP5JUN1950 MP5
ln -s $DATADIR/MP6JUN1950 MP6
ln -s $DATADIR/PRECJUN1950 PREC
ln -s $DATADIR/PSJUN1950 PS
ln -s $DATADIR/QFOLJUN1950 QFOL
ln -s $DATADIR/QLATJUN1950 QLAT
ln -s $DATADIR/QSENJUN1950 QSEN
ln -s $DATADIR/SATJUN1950 SAT
ln -s $DATADIR/SIC1JUN1950 SIC1
ln -s $DATADIR/SIC2JUN1950 SIC2
ln -s $DATADIR/SIC3JUN1950 SIC3
ln -s $DATADIR/SIC4JUN1950 SIC4
ln -s $DATADIR/SIC5JUN1950 SIC5
ln -s $DATADIR/SIC6JUN1950 SIC6
ln -s $DATADIR/TPJUN1950 TP
ln -s $DATADIR/USJUN1950 US
ln -s $DATADIR/VISJUN1950 VIS
ln -s $DATADIR/VSJUN1950 VS
ln -s $DATADIR/ZENJUN1950 ZEN
#ln -s $DATADIR/SOILT30cmJUN1950 SOILT30cm
#ln -s $DATADIR/SMOIST30cmJUN1950 SMOIST30cm

# hack to provide missing input files
if [ -f $DATADIR/SOILT_dummy_1 ] ; then
# dummy files are present
ln -s $DATADIR/SOILT_dummy_1 SOILT1
ln -s $DATADIR/SOILT_dummy_2 SOILT2
ln -s $DATADIR/SOILT_dummy_3 SOILT3
ln -s $DATADIR/SOILT_dummy_4 SOILT4
ln -s $DATADIR/SOILT_dummy_5 SOILT5
ln -s $DATADIR/SOILT_dummy_6 SOILT6
ln -s $DATADIR/SMOIST_dummy_1 W1
ln -s $DATADIR/SMOIST_dummy_2 W2
ln -s $DATADIR/SMOIST_dummy_3 W3
ln -s $DATADIR/SMOIST_dummy_4 W4
ln -s $DATADIR/SMOIST_dummy_5 W5
ln -s $DATADIR/SMOIST_dummy_6 W6
else
# try to link all to an existing file (will not work with some compilers)
ln -s $DATADIR/SOILT30cmJUN1950 SOILT1
ln -s $DATADIR/SOILT30cmJUN1950 SOILT2
ln -s $DATADIR/SOILT30cmJUN1950 SOILT3
ln -s $DATADIR/SOILT30cmJUN1950 SOILT4
ln -s $DATADIR/SOILT30cmJUN1950 SOILT5
ln -s $DATADIR/SOILT30cmJUN1950 SOILT6
ln -s $DATADIR/SMOIST30cmJUN1950 W1
ln -s $DATADIR/SMOIST30cmJUN1950 W2
ln -s $DATADIR/SMOIST30cmJUN1950 W3
ln -s $DATADIR/SMOIST30cmJUN1950 W4
ln -s $DATADIR/SMOIST30cmJUN1950 W5
ln -s $DATADIR/SMOIST30cmJUN1950 W6
fi

./ent


rm -f CH
rm -f DVIS
rm -f MP1
rm -f MP2
rm -f MP3
rm -f MP4
rm -f MP5
rm -f MP6
rm -f PREC
rm -f PS
rm -f QFOL
rm -f QLAT
rm -f QSEN
rm -f SAT
rm -f SIC1
rm -f SIC2
rm -f SIC3
rm -f SIC4
rm -f SIC5
rm -f SIC6
rm -f TP
rm -f US
rm -f VIS
rm -f VS
rm -f ZEN
#rm -f SOILT30cm
#rm -f SMOIST30cm

rm -r SOILT1
rm -r SOILT2
rm -r SOILT3
rm -r SOILT4
rm -r SOILT5
rm -r SOILT6
rm -r W1
rm -r W2
rm -r W3
rm -r W4
rm -r W5
rm -r W6

rm -f VEG
rm -f CROPS
rm -f soil_textures


